CREATE TABLE IF NOT EXISTS `Cortes` (
    `hora_inicio` TIME NOT NULL,
    `hora_final` TIME NOT NULL,
    `dia` DATE NOT NULL,
    `bloque` VARCHAR(24) NOT NULL,
    `subestacion` INT NOT NULL,
    `primarios_a_desconectar` VARCHAR(255),
    `equipo_abrir` INT,
    `equipo_transf` INT,
    `carga_est_mw` FLOAT NOT NULL,
    `provincia` VARCHAR(255) NOT NULL,
    `canton` VARCHAR(255) NOT NULL,
    `zona` LONGTEXT,
    `sectores` LONGTEXT,
    `prevalencia_del_alimentador` VARCHAR(255),
    `numero_clientes` INT NOT NULL,
    `clientes_residenciales` INT NOT NULL,
    `aporte_residencial` FLOAT NOT NULL,
    `clientes_comerciales` INT NOT NULL,
    `aporte_comercial` FLOAT NOT NULL,
    `clientes_industriales` INT NOT NULL,
    `aporte_industrial` FLOAT NOT NULL,
    PRIMARY KEY (`hora_inicio`, `hora_final`, `dia`, `primarios_a_desconectar`, `provincia`, `canton`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
